import { matchPath } from 'react-router-dom';

export type SurfaceClass = 'gateway' | 'core' | 'secondary' | 'operational' | 'hidden' | 'fallback';
export type CenterActionPolicy = 'new-entry-default' | 'select-entries-for-discussion';

export type RouteSurfaceSpec = {
  id: string;
  path: string;
  surfaceClass: SurfaceClass;
  showBottomNav: boolean;
  showFloatingChatButton: boolean;
  showFeedbackTrigger: boolean;
  centerActionPolicy: CenterActionPolicy;
};

export const ROUTE_SURFACE_REGISTRY: RouteSurfaceSpec[] = [
  {
    id: 'onboarding',
    path: '/onboarding',
    surfaceClass: 'gateway',
    showBottomNav: false,
    showFloatingChatButton: false,
    showFeedbackTrigger: false,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'auth',
    path: '/auth',
    surfaceClass: 'gateway',
    showBottomNav: false,
    showFloatingChatButton: false,
    showFeedbackTrigger: true,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'admin-dashboard',
    path: '/admin/dashboard',
    surfaceClass: 'operational',
    showBottomNav: false,
    showFloatingChatButton: false,
    showFeedbackTrigger: false,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'admin-feedback',
    path: '/admin/feedback',
    surfaceClass: 'operational',
    showBottomNav: false,
    showFloatingChatButton: false,
    showFeedbackTrigger: false,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'admin-system',
    path: '/admin/system',
    surfaceClass: 'operational',
    showBottomNav: false,
    showFloatingChatButton: false,
    showFeedbackTrigger: false,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'admin-crashes',
    path: '/admin/crashes',
    surfaceClass: 'operational',
    showBottomNav: false,
    showFloatingChatButton: false,
    showFeedbackTrigger: false,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'admin-analytics',
    path: '/admin/analytics',
    surfaceClass: 'operational',
    showBottomNav: false,
    showFloatingChatButton: false,
    showFeedbackTrigger: false,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'admin-login',
    path: '/admin',
    surfaceClass: 'operational',
    showBottomNav: false,
    showFloatingChatButton: false,
    showFeedbackTrigger: false,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'ethereal-situations-game',
    path: '/e/games/situations/:sessionId',
    surfaceClass: 'hidden',
    showBottomNav: false,
    showFloatingChatButton: false,
    showFeedbackTrigger: false,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'ethereal-home',
    path: '/e/home',
    surfaceClass: 'hidden',
    showBottomNav: false,
    showFloatingChatButton: false,
    showFeedbackTrigger: false,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'ethereal-chat',
    path: '/e/chat',
    surfaceClass: 'hidden',
    showBottomNav: false,
    showFloatingChatButton: false,
    showFeedbackTrigger: false,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'ethereal-chronicles',
    path: '/e/chronicles',
    surfaceClass: 'hidden',
    showBottomNav: false,
    showFloatingChatButton: false,
    showFeedbackTrigger: false,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'ethereal-tasks',
    path: '/e/tasks',
    surfaceClass: 'hidden',
    showBottomNav: false,
    showFloatingChatButton: false,
    showFeedbackTrigger: false,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'ethereal-calendar',
    path: '/e/calendar',
    surfaceClass: 'hidden',
    showBottomNav: false,
    showFloatingChatButton: false,
    showFeedbackTrigger: false,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'ethereal-games',
    path: '/e/games',
    surfaceClass: 'hidden',
    showBottomNav: false,
    showFloatingChatButton: false,
    showFeedbackTrigger: false,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'ethereal-gate',
    path: '/e',
    surfaceClass: 'hidden',
    showBottomNav: false,
    showFloatingChatButton: false,
    showFeedbackTrigger: false,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'receipt-scan',
    path: '/receipts/scan',
    surfaceClass: 'secondary',
    showBottomNav: false,
    showFloatingChatButton: true,
    showFeedbackTrigger: true,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'receipt-review',
    path: '/receipts/review',
    surfaceClass: 'secondary',
    showBottomNav: false,
    showFloatingChatButton: true,
    showFeedbackTrigger: true,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'receipt-analytics',
    path: '/receipts/analytics',
    surfaceClass: 'secondary',
    showBottomNav: false,
    showFloatingChatButton: true,
    showFeedbackTrigger: true,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'receipt-detail',
    path: '/receipts/:id',
    surfaceClass: 'secondary',
    showBottomNav: false,
    showFloatingChatButton: true,
    showFeedbackTrigger: true,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'receipts',
    path: '/receipts',
    surfaceClass: 'secondary',
    showBottomNav: false,
    showFloatingChatButton: true,
    showFeedbackTrigger: true,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'discussion-detail',
    path: '/discussions/:id',
    surfaceClass: 'secondary',
    showBottomNav: false,
    showFloatingChatButton: false,
    showFeedbackTrigger: false,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'entry-edit',
    path: '/entry/:id',
    surfaceClass: 'core',
    showBottomNav: false,
    showFloatingChatButton: false,
    showFeedbackTrigger: false,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'reminder-detail',
    path: '/reminder/:id',
    surfaceClass: 'secondary',
    showBottomNav: true,
    showFloatingChatButton: true,
    showFeedbackTrigger: true,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'day-view',
    path: '/day/:date',
    surfaceClass: 'core',
    showBottomNav: true,
    showFloatingChatButton: true,
    showFeedbackTrigger: true,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'today',
    path: '/',
    surfaceClass: 'core',
    showBottomNav: true,
    showFloatingChatButton: true,
    showFeedbackTrigger: true,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'calendar',
    path: '/calendar',
    surfaceClass: 'core',
    showBottomNav: true,
    showFloatingChatButton: true,
    showFeedbackTrigger: true,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'search',
    path: '/search',
    surfaceClass: 'secondary',
    showBottomNav: true,
    showFloatingChatButton: true,
    showFeedbackTrigger: true,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'chat',
    path: '/chat',
    surfaceClass: 'secondary',
    showBottomNav: true,
    showFloatingChatButton: false,
    showFeedbackTrigger: true,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'discussions',
    path: '/discussions',
    surfaceClass: 'secondary',
    showBottomNav: true,
    showFloatingChatButton: true,
    showFeedbackTrigger: true,
    centerActionPolicy: 'select-entries-for-discussion',
  },
  {
    id: 'settings',
    path: '/settings',
    surfaceClass: 'core',
    showBottomNav: true,
    showFloatingChatButton: true,
    showFeedbackTrigger: true,
    centerActionPolicy: 'new-entry-default',
  },
  {
    id: 'new-entry',
    path: '/new',
    surfaceClass: 'core',
    showBottomNav: false,
    showFloatingChatButton: false,
    showFeedbackTrigger: false,
    centerActionPolicy: 'new-entry-default',
  },
];

export const FALLBACK_ROUTE_SURFACE_SPEC: RouteSurfaceSpec = {
  id: 'fallback',
  path: '*',
  surfaceClass: 'fallback',
  showBottomNav: true,
  showFloatingChatButton: true,
  showFeedbackTrigger: true,
  centerActionPolicy: 'new-entry-default',
};

export function resolveRouteSurface(pathname: string): RouteSurfaceSpec {
  for (const spec of ROUTE_SURFACE_REGISTRY) {
    if (matchPath({ path: spec.path, end: true }, pathname)) {
      return spec;
    }
  }

  return FALLBACK_ROUTE_SURFACE_SPEC;
}
